In [38]:
import pandas as pd

In [39]:
data = pd.read_csv("Airline_Delay_Cause.csv")

In [40]:
data.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,5,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",136.0,7.0,5.95,0.00,...,0.0,1.00,0.0,0.0,255.0,222.0,0.0,4.0,0.0,29.0
1,2022,5,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",91.0,16.0,7.38,0.00,...,0.0,6.09,0.0,0.0,884.0,351.0,0.0,81.0,0.0,452.0
2,2022,5,9E,Endeavor Air Inc.,ACK,"Nantucket, MA: Nantucket Memorial",19.0,2.0,0.13,0.00,...,0.0,0.88,1.0,0.0,138.0,4.0,0.0,106.0,0.0,28.0
3,2022,5,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",88.0,14.0,7.26,0.76,...,0.0,1.64,0.0,0.0,947.0,585.0,35.0,125.0,0.0,202.0
4,2022,5,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",181.0,19.0,13.84,0.00,...,0.0,2.09,0.0,0.0,808.0,662.0,0.0,87.0,0.0,59.0

In [41]:
data.isna().sum()

year                     0
month                    0
carrier                  4
carrier_name             4
airport                  3
airport_name             0
arr_flights            493
arr_del15              732
carrier_ct             492
weather_ct             494
nas_ct                 488
security_ct            488
late_aircraft_ct       488
arr_cancelled          488
arr_diverted           490
arr_delay              494
carrier_delay          492
weather_delay          488
nas_delay              488
security_delay         490
late_aircraft_delay    488
dtype: int64

In [42]:
data.dropna(inplace=True)

In [43]:
data.isna().sum()

year                   0
month                  0
carrier                0
carrier_name           0
airport                0
airport_name           0
arr_flights            0
arr_del15              0
carrier_ct             0
weather_ct             0
nas_ct                 0
security_ct            0
late_aircraft_ct       0
arr_cancelled          0
arr_diverted           0
arr_delay              0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 317261 entries, 0 to 318016
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 317261 non-null  int64
 1   month                317261 non-null  int64
 2   carrier              317261 non-null  object
 3   carrier_name         317261 non-null  object
 4   airport              317261 non-null  object
 5   airport_name         317261 non-null  object
 6   arr_flights          317261 non-null  float64
 7   arr_del15            317261 non-null  float64
 8   carrier_ct           317261 non-null  float64
 9   weather_ct           317261 non-null  float64
 10  nas_ct               317261 non-null  float64
 11  security_ct          317261 non-null  float64
 12  late_aircraft_ct     317261 non-null  float64
 13  arr_cancelled        317261 non-null  float64
 14  arr_diverted         317261 non-null  float64
 15  arr_delay            317261 non-null  float64
 16  carrier_delay        317261 non-null  float64
 17  weather_delay        317261 non-null  float64
 18  nas_delay            317261 non-null  float64
 19  security_delay       317261 non-null  float64
 20  late_aircraft_delay  317261 non-null  float64
dtypes: float64(15), int64(2), object(4)
memory usage: 53.3+ MB

In [45]:
data.drop(['carrier','carrier_name','airport','airport_name'],axis=1,inplace=True)

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 317261 entries, 0 to 318016
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 317261 non-null  int64
 1   month                317261 non-null  int64
 2   arr_flights          317261 non-null  float64
 3   arr_del15            317261 non-null  float64
 4   carrier_ct           317261 non-null  float64
 5   weather_ct           317261 non-null  float64
 6   nas_ct               317261 non-null  float64
 7   security_ct          317261 non-null  float64
 8   late_aircraft_ct     317261 non-null  float64
 9   arr_cancelled        317261 non-null  float64
 10  arr_diverted         317261 non-null  float64
 11  arr_delay            317261 non-null  float64
 12  carrier_delay        317261 non-null  float64
 13  weather_delay        317261 non-null  float64
 14  nas_delay            317261 non-null  float64
 15  security_delay       317261 non-null  float64
 16  late_aircraft_delay  317261 non-null  float64
dtypes: float64(15), int64(2)
memory usage: 43.6 MB

In [47]:
data

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,5,136.0,7.0,5.95,0.00,0.05,0.0,1.00,0.0,0.0,255.0,222.0,0.0,4.0,0.0,29.0
1,2022,5,91.0,16.0,7.38,0.00,2.54,0.0,6.09,0.0,0.0,884.0,351.0,0.0,81.0,0.0,452.0
2,2022,5,19.0,2.0,0.13,0.00,1.00,0.0,0.88,1.0,0.0,138.0,4.0,0.0,106.0,0.0,28.0
3,2022,5,88.0,14.0,7.26,0.76,4.35,0.0,1.64,0.0,0.0,947.0,585.0,35.0,125.0,0.0,202.0
4,2022,5,181.0,19.0,13.84,0.00,3.07,0.0,2.09,0.0,0.0,808.0,662.0,0.0,87.0,0.0,59.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318012,2003,6,480.0,84.0,25.69,3.09,33.96,0.0,21.26,0.0,0.0,3744.0,978.0,164.0,1023.0,0.0,1579.0
318013,2003,6,505.0,111.0,21.78,2.24,73.81,0.0,13.17,3.0,0.0,4284.0,1376.0,138.0,2132.0,0.0,638.0
318014,2003,6,146.0,36.0,6.99,0.00,26.85,0.0,2.15,0.0,0.0,896.0,205.0,0.0,607.0,0.0,84.0
318015,2003,6,95.0,13.0,3.66,0.00,7.92,0.0,1.42,0.0,0.0,367.0,120.0,0.0,210.0,0.0,37.0
318016,2003,6,3466.0,454.0,121.15,7.61,221.91,1.0,102.33,9.0,0.0,16853.0,5384.0,306.0,5686.0,28.0,5449.0

In [48]:
X = data.drop(['late_aircraft_ct'],axis = 1,inplace = False)
y = data['late_aircraft_ct']

In [49]:
data.head()

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,5,136.0,7.0,5.95,0.00,0.05,0.0,1.00,0.0,0.0,255.0,222.0,0.0,4.0,0.0,29.0
1,2022,5,91.0,16.0,7.38,0.00,2.54,0.0,6.09,0.0,0.0,884.0,351.0,0.0,81.0,0.0,452.0
2,2022,5,19.0,2.0,0.13,0.00,1.00,0.0,0.88,1.0,0.0,138.0,4.0,0.0,106.0,0.0,28.0
3,2022,5,88.0,14.0,7.26,0.76,4.35,0.0,1.64,0.0,0.0,947.0,585.0,35.0,125.0,0.0,202.0
4,2022,5,181.0,19.0,13.84,0.00,3.07,0.0,2.09,0.0,0.0,808.0,662.0,0.0,87.0,0.0,59.0

In [50]:
X.head()

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2022,5,136.0,7.0,5.95,0.00,0.05,0.0,0.0,0.0,255.0,222.0,0.0,4.0,0.0,29.0
1,2022,5,91.0,16.0,7.38,0.00,2.54,0.0,0.0,0.0,884.0,351.0,0.0,81.0,0.0,452.0
2,2022,5,19.0,2.0,0.13,0.00,1.00,0.0,1.0,0.0,138.0,4.0,0.0,106.0,0.0,28.0
3,2022,5,88.0,14.0,7.26,0.76,4.35,0.0,0.0,0.0,947.0,585.0,35.0,125.0,0.0,202.0
4,2022,5,181.0,19.0,13.84,0.00,3.07,0.0,0.0,0.0,808.0,662.0,0.0,87.0,0.0,59.0

In [51]:
X.shape

(317261, 16)

In [52]:
y

0           1.00
1           6.09
2           0.88
3           1.64
4           2.09
           ...
318012     21.26
318013     13.17
318014      2.15
318015      1.42
318016    102.33
Name: late_aircraft_ct, Length: 317261, dtype: float64

In [53]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=44, shuffle =True)

#Splitted Data

print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
print('y_train shape is ' , y_train.shape)
print('y_test shape is ' , y_test.shape)

X_train shape is  (237945, 16)
X_test shape is  (79316, 16)
y_train shape is  (237945,)
y_test shape is  (79316,)

In [54]:
from sklearn.linear_model import LinearRegression

In [56]:
LinearRegressionModel = LinearRegression(fit_intercept=True, copy_X=True, n_jobs=-1)

In [57]:
%%time
LinearRegressionModel.fit(X_train, y_train)
# y = t1x1 + t2x2 + . . . . . t16x16
# y = 0.98x1 + 0.836x2 + . . . . . 0.362x16

CPU times: total: 469 ms
Wall time: 261 ms

LinearRegression(n_jobs=-1)

In [59]:
X_train.head()

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
35198,2020,8,701.0,105.0,20.84,25.60,19.21,0.0,31.0,3.0,7199.0,2194.0,1250.0,1370.0,0.0,2385.0
211991,2009,5,56.0,13.0,1.49,0.74,0.91,0.0,1.0,1.0,523.0,174.0,20.0,30.0,0.0,299.0
115015,2015,8,111.0,14.0,8.86,0.00,2.58,0.0,1.0,1.0,1081.0,839.0,0.0,88.0,0.0,154.0
147187,2013,5,1334.0,298.0,44.91,10.51,146.49,0.0,30.0,4.0,18814.0,2138.0,569.0,8893.0,0.0,7214.0
249392,2007,5,31.0,16.0,5.84,2.28,2.85,0.0,0.0,0.0,1122.0,287.0,216.0,100.0,0.0,519.0

In [60]:
y_train.head()

35198     39.35
211991     9.86
115015     2.56
147187    96.09
249392     5.02
Name: late_aircraft_ct, dtype: float64

In [61]:
y_pred = LinearRegressionModel.predict(X_test)
y_pred

array([1.48100667e+01, 2.30900480e+01, 3.83200543e+01, ...,
       1.80000684e+01, 7.61379454e-05, 5.80000341e+01])

In [62]:
list(y_pred)

[np.float64(14.810066691840586),
 np.float64(23.090047967658546),
 np.float64(38.32005434123113),
 np.float64(15.930078774069447),
 np.float64(9.900074565043184),
 np.float64(24.160075487108355),
 np.float64(15.310024245618498),
 np.float64(44.77005529831358),
 np.float64(2.9700747347325667),
 np.float64(18.4500634386525),
 np.float64(393.65964535836906),
 np.float64(7.140056844674685),
 np.float64(8.062995368274609e-05),
 np.float64(4.040071546152578),
 np.float64(4.000081126644783),
 np.float64(257.2000752037017),
 np.float64(2.750076768290266),
 np.float64(37.56005951816201),
 np.float64(35.620006449881586),
 np.float64(7.152853352791061e-05),
 np.float64(41.10004982495397),
 np.float64(3.0500747556566212),
 np.float64(7.252648963432251e-05),
 np.float64(0.7800767855267755),
 np.float64(13.65007740707773),
 np.float64(8.21431029498932e-05),
 np.float64(7.84176719472729e-05),
 np.float64(15.030047476984974),
 np.float64(3.1700773616221065),
 np.float64(5.300072029156194),
 np.float64(4.350076084167481),
 np.float64(8.610055310585546),
 np.float64(11.430072654855612),
 np.float64(38.95004022921192),
 np.float64(7.683476940354155e-05),
 np.float64(12.980078269072688),
 np.float64(7.555464548026497e-05),
 np.float64(3.9900826438406116),
 np.float64(16.80007104273441),
 np.float64(16.49005097734746),
 np.float64(20.33007647744755),
 np.float64(-0.009932614320283473),
 np.float64(2.0000789563734984),
 np.float64(29.639985404382333),
 np.float64(1.9400787798876058),
 np.float64(6.330083849672643),
 np.float64(8.570069056812894),
 np.float64(9.440061734835618),
 np.float64(7.460083104573069),
 np.float64(55.92003216964807),
 np.float64(7.000066310346081),
 np.float64(0.6800809329796116),
 np.float64(2.3500681934862935),
 np.float64(13.870085829156942),
 np.float64(28.220055507066032),
 np.float64(5.310082023959685),
 np.float64(0.6900833447107653),
 np.float64(277.0700771594423),
 np.float64(29.000067820253975),
 np.float64(6.400070737908578),
 np.float64(2.3500795918871615),
 np.float64(2.840081297284911),
 np.float64(1.0000755890974424),
 np.float64(18.580054358922194),
 np.float64(0.8600820309828355),
 np.float64(96.96005257099445),
 np.float64(7.460073895740729),
 np.float64(5.380085550286432),
 np.float64(0.720072405170817),
 np.float64(2.080074226467062),
 np.float64(13.430077094707292),
 np.float64(40.43003865336408),
 np.float64(6.780079797011915),
 np.float64(8.263879197297321e-05),
 np.float64(500.2902185040426),
 np.float64(23.520078398535198),
 np.float64(0.9600786467406034),
 np.float64(10.450062508866159),
 np.float64(0.11007079871492763),
 np.float64(20.950058588470345),
 np.float64(8.940071197784683),
 np.float64(5.580060748623421),
 np.float64(5.380075691152985),
 np.float64(20.820078817530188),
 np.float64(6.770068756786966),
 np.float64(65.18005180570121),
 np.float64(8.710071961980645),
 np.float64(8.096548284196314e-05),
 np.float64(1.78005136886372),
 np.float64(0.8500673038676112),
 np.float64(22.71007562486618),
 np.float64(4.180076797378435),
 np.float64(8.13233589544585e-05),
 np.float64(5.96007255847491),
 np.float64(0.8700763742562102),
 np.float64(10.480047881457754),
 np.float64(26.38005695730275),
 np.float64(5.860074327528944),
 np.float64(15.200041939121617),
 np.float64(12.320058346506361),
 np.float64(7.690079991240646),
 np.float64(24.89003735174226),
 np.float64(8.2791203798456e-05),
 np.float64(0.33007411520665797),
 np.float64(6.4900778119464215),
 np.float64(26.41005576476206),
 np.float64(7.32007338292441),
 np.float64(3.7800671645941204),
 np.float64(9.0700734692512),
 np.float64(12.84005362011553),
 np.float64(3.0000602581031415),
 np.float64(1.5800696273742485),
 np.float64(1.5300444903922263),
 np.float64(2.00006562644952),
 np.float64(34.2600180881184),
 np.float64(0.05007481348061271),
 np.float64(9.030077049391476),
 np.float64(7.620048242010929),
 np.float64(76.44010047494712),
 np.float64(6.600078415040794),
 np.float64(2.4600749224774887),
 np.float64(7.766560133704026e-05),
 np.float64(4.290077805222093),
 np.float64(1.0000728629248143),
 np.float64(31.78005026537107),
 np.float64(7.02493500032153e-05),
 np.float64(48.99007416369059),
 np.float64(18.930066975592833),
 np.float64(13.090044253062597),
 np.float64(1.0000766446357432),
 np.float64(6.550067865683049),
 np.float64(2.490062421610413),
 np.float64(5.300077881059707),
 np.float64(8.053776323642403e-05),
 np.float64(15.350071084593852),
 np.float64(2.100083460661362),
 np.float64(4.2200830960237585),
 np.float64(8.030874838840796e-05),
 np.float64(16.250077306559678),
 np.float64(2.0100566019881225),
 np.float64(10.800074747737998),
 np.float64(10.630066054123073),
 np.float64(27.61006708832015),
 np.float64(0.870073696079164),
 np.float64(16.770057696493563),
 np.float64(1.9100750499500854),
 np.float64(2.000054043021826),
 np.float64(1.0000745342934623),
 np.float64(15.810054702958421),
 np.float64(10.520062525288834),
 np.float64(12.960063010433768),
 np.float64(16.90007479195859),
 np.float64(408.34996954458336),
 np.float64(0.46007030386933034),
 np.float64(137.87010923121198),
 np.float64(28.430062171465917),
 np.float64(19.460067409490165),
 np.float64(8.070075402907419),
 np.float64(3.9900152127197823),
 np.float64(3.1900681489561906),
 np.float64(7.531588165840541e-05),
 np.float64(72.68008434914121),
 np.float64(12.7400702753849),
 np.float64(1.0000746479118512),
 np.float64(86.14004995094763),
 np.float64(15.110066761515771),
 np.float64(2.830079938040769),
 np.float64(16.04006210617096),
 np.float64(16.210053602183965),
 np.float64(6.020079215329847),
 np.float64(3.5600677224154036),
 np.float64(16.180037559617997),
 np.float64(7.530078333057338),
 np.float64(0.6300718507572758),
 np.float64(0.7900768715918711),
 np.float64(8.131178716450213e-05),
 np.float64(4.500079999610713),
 np.float64(3.790070890518998),
 np.float64(1.94006623642745),
 np.float64(37.98005306408375),
 np.float64(8.830072130547372),
 np.float64(7.760063289722396),
 np.float64(7.926223624693529e-05),
 np.float64(5.870040165736411),
 np.float64(17.820097298426695),
 np.float64(10.630054604415193),
 np.float64(8.361926121566352e-05),
 np.float64(0.11008148103363363),
 np.float64(44.08009782952881),
 np.float64(2.630075637685887),
 np.float64(9.950066408477145),
 np.float64(26.730069816499384),
 np.float64(8.690062578162163),
 np.float64(41.2200843570799),
 np.float64(39.63004006712606),
 np.float64(7.69378842645739e-05),
 np.float64(33.960050759327984),
 np.float64(17.450079200281827),
 np.float64(20.040056053552842),
 np.float64(18.17005985247229),
 np.float64(4.070075312833177),
 np.float64(131.4800565214969),
 np.float64(30.00003551074798),
 np.float64(4.950075588947325),
 np.float64(0.010074973493671258),
 np.float64(159.74006400465737),
 np.float64(6.427282164445103e-05),
 np.float64(0.5500788580286256),
 np.float64(68.13001783549802),
 np.float64(10.260070421245254),
 np.float64(0.9900710283761135),
 np.float64(10.660085719718326),
 np.float64(2.6000806272526327),
 np.float64(2.6000732320310407),
 np.float64(570.1899841611533),
 np.float64(3.710070950559337),
 np.float64(11.22007347701861),
 np.float64(7.670075871328454),
 np.float64(9.060048699465762),
 np.float64(14.110057254138804),
 np.float64(86.82001530874938),
 np.float64(7.517421687525117e-05),
 np.float64(12.81006589504527),
 np.float64(2.0600719161371077),
 np.float64(7.730055122071094),
 np.float64(2.610078086549395),
 np.float64(1.980074386925603),
 np.float64(8.020057950679929),
 np.float64(1.4700851422748678),
 np.float64(44.50002487586639),
 np.float64(85.16004726680801),
 np.float64(12.8300750150267),
 np.float64(15.080062273048087),
 np.float64(30.710037819415408),
 np.float64(6.870067921953048),
 np.float64(18.010068033553146),
 np.float64(7.040486083806363e-05),
 np.float64(4.0000540733632794),
 np.float64(4.190068807283026),
 np.float64(3.260073024616504),
 np.float64(8.227873275712394e-05),
 np.float64(22.00004581586482),
 np.float64(172.45004335667932),
 np.float64(5.650073109956115),
 np.float64(8.18007252836165),
 np.float64(6.0000563697044),
 np.float64(6.345481819927667e-05),
 np.float64(21.380044876903),
 np.float64(29.180063026440166),
 np.float64(21.850023968279526),
 np.float64(3.830076736819257),
 np.float64(1.480071718187034),
 np.float64(65.90008553610791),
 np.float64(13.000069519627052),
 np.float64(4.16007276976055),
 np.float64(1.7000842650520533),
 np.float64(18.110077764240007),
 np.float64(6.640080046938475),
 np.float64(15.720072326192842),
 np.float64(136.34002399119413),
 np.float64(12.100071900000094),
 np.float64(2.0200811968087904),
 np.float64(14.650059177088902),
 np.float64(3.260068500440793),
 np.float64(1.0000727480387517),
 np.float64(464.20005460452404),
 np.float64(3.140072349794823),
 np.float64(4.000028098546363),
 np.float64(1.490077228375339),
 np.float64(12.000057865838363),
 np.float64(34.6500560352237),
 np.float64(16.10005400014126),
 np.float64(15.900053477193143),
 np.float64(6.600053029787449),
 np.float64(0.7500659495656806),
 np.float64(16.940059806973935),
 np.float64(3.0000851839045533),
 np.float64(3.970059440127695),
 np.float64(4.750084258858743),
 np.float64(4.880064735563345),
 np.float64(8.760069817176552),
 np.float64(20.600014006747397),
 np.float64(8.34007870916643),
 np.float64(26.60007199816595),
 np.float64(9.580071986095838),
 np.float64(17.610076178148713),
 np.float64(0.9000782075189099),
 np.float64(24.800058831777978),
 np.float64(60.850063560322724),
 np.float64(11.530077877545647),
 np.float64(9.390074522286351),
 np.float64(1.4400735000272769),
 np.float64(7.905390827968317e-05),
 np.float64(8.29570804991239e-05),
 np.float64(12.350065393701234),
 np.float64(8.140077511321685),
 np.float64(2.920072274606981),
 np.float64(4.8230813748162404e-05),
 np.float64(8.03001995857311),
 np.float64(9.850073759419114),
 np.float64(8.256832171936023e-05),
 np.float64(1.5800779700463012),
 np.float64(0.8300767885793795),
 np.float64(7.179471993046249e-05),
 np.float64(12.900065717775215),
 np.float64(7.380439675984396e-05),
 np.float64(31.11004913106582),
 np.float64(3.39007709834012),
 np.float64(1.0000678649459085),
 np.float64(16.110069604653994),
 np.float64(3.5500683771116366),
 np.float64(7.070078037484171),
 np.float64(11.290047801965212),
 np.float64(7.839958193731067e-05),
 np.float64(2.430077645786025),
 np.float64(2.7500763811484426),
 np.float64(2.5800715133509238),
 np.float64(6.362957692190863e-05),
 np.float64(8.710071570711706),
 np.float64(11.310063080251593),
 np.float64(17.82006268477104),
 np.float64(10.120063302573016),
 np.float64(11.740062694097999),
 np.float64(1.000076836658001),
 np.float64(28.000048400975647),
 np.float64(0.8000802352167786),
 np.float64(1.1600682856317879),
 np.float64(98.72006203216013),
 np.float64(15.000066741447801),
 np.float64(2.6200803397535157),
 np.float64(5.560071598453124),
 np.float64(3.490068985939889),
 np.float64(32.11005181979746),
 np.float64(8.000053633462997),
 np.float64(1.7900761904388867),
 np.float64(16.720069636029987),
 np.float64(4.740075183573634),
 np.float64(795.9998391865003),
 np.float64(138.0900462030599),
 np.float64(69.06004719164055),
 np.float64(8.260058983782582),
 np.float64(62.66002883788299),
 np.float64(10.470056381578472),
 np.float64(4.280080829421653),
 np.float64(4.750077076947644),
 np.float64(1.6600840485271016),
 np.float64(10.310072435073149),
 np.float64(1.000077038106566),
 np.float64(1.4300609190683398),
 np.float64(8.371933473432717e-05),
 np.float64(3.780077312425142),
 np.float64(6.010082700430949),
 np.float64(4.160073299244377),
 np.float64(3.4900684969072735),
 np.float64(6.171255730763603e-05),
 np.float64(1.4400612566862205),
 np.float64(4.220077160358366),
 np.float64(3.6700741178524914),
 np.float64(14.880061208336768),
 np.float64(9.160074656989233),
 np.float64(8.485864253885756e-05),
 np.float64(5.460042127615185),
 np.float64(14.810059480221542),
 np.float64(18.76007717742242),
 np.float64(8.003921292418226e-05),
 np.float64(15.410045382081078),
 np.float64(4.7500729660782905),
 np.float64(5.860069125077867),
 np.float64(15.540075228370752),
 np.float64(2.960075946121361),
 np.float64(25.46004307355794),
 np.float64(0.7600837305278692),
 np.float64(8.380065831848025),
 np.float64(3.4800783936286694),
 np.float64(6.970071583289414),
 np.float64(70.57994070418734),
 np.float64(2.490064591895861),
 np.float64(5.800055883826952),
 np.float64(7.80558625839145e-05),
 np.float64(25.00003916473305),
 np.float64(312.89005986023324),
 np.float64(30.04005913943053),
 np.float64(6.250074433521953),
 np.float64(4.670049681559751),
 np.float64(14.900051801462457),
 np.float64(31.300064435519282),
 np.float64(1.2000462099646645),
 np.float64(1.7800798002390188),
 np.float64(9.38007422250847),
 np.float64(6.2500780839057715),
 np.float64(64.28005329999584),
 np.float64(1.3100746779420893),
 np.float64(16.75006939213081),
 np.float64(7.875023691006344e-05),
 np.float64(12.480054276042694),
 np.float64(2.000073913592971),
 np.float64(10.560085174734954),
 np.float64(9.89006779921153),
 np.float64(0.9300787500951603),
 np.float64(8.106591978643968e-05),
 np.float64(1.000074917702791),
 np.float64(1.0000740568624824),
 np.float64(3.3800707344340055),
 np.float64(1.0000689290979552),
 np.float64(9.630079968057828),
 np.float64(3.9700642150191516),
 np.float64(1.0000723737055366),
 np.float64(0.6300636496940694),
 np.float64(9.630076149079242),
 np.float64(8.304725805627355e-05),
 np.float64(6.868761796013922e-05),
 np.float64(4.320077587566748),
 np.float64(21.930066156852572),
 np.float64(62.77002217010961),
 np.float64(145.5300289246824),
 np.float64(6.230073069702237),
 np.float64(16.76006581823754),
 np.float64(6.700065826479365),
 np.float64(85.99998384331839),
 np.float64(16.540037206800598),
 np.float64(5.1883406936736876e-05),
 np.float64(13.110072708999287),
 np.float64(22.720080906080707),
 np.float64(7.410065311348352),
 np.float64(9.010042987088953),
 np.float64(2.510062683934364),
 np.float64(13.010079424671432),
 np.float64(10.560053586542628),
 np.float64(2.730071129286435),
 np.float64(2.1400498035245685),
 np.float64(2.920076670058052),
 np.float64(1.0000748822239118),
 np.float64(0.05008277782327414),
 np.float64(2.2500789168854314),
 np.float64(12.750049727022008),
 np.float64(16.56008042003946),
 np.float64(13.220076012673053),
 np.float64(45.110006797010485),
 np.float64(9.75007580442526),
 np.float64(7.280066333849121),
 np.float64(10.31008111734499),
 np.float64(6.320788074398731e-05),
 np.float64(12.970078432839674),
 np.float64(4.830072310604445),
 np.float64(0.9000738445383928),
 np.float64(14.68007085552097),
 np.float64(1.0000635052491529),
 np.float64(21.28006157205525),
 np.float64(11.390069624756828),
 np.float64(3.000067199091812),
 np.float64(23.400481576814364),
 np.float64(0.0800774546999892),
 np.float64(16.190067874181235),
 np.float64(8.156054162063164e-05),
 np.float64(8.320055537732204),
 np.float64(25.580075774831467),
 np.float64(14.730069084301016),
 np.float64(268.43995725055754),
 np.float64(1.370084610777066),
 np.float64(3.520080605520445),
 np.float64(1.0400739875131162),
 np.float64(37.94003393442512),
 np.float64(10.050074289939767),
 np.float64(8.420067251712052),
 np.float64(79.78997857443575),
 np.float64(32.320055575051185),
 np.float64(94.62000596223736),
 np.float64(83.41000961793729),
 np.float64(56.740070998427726),
 np.float64(7.240083739356346),
 np.float64(70.90003903589077),
 np.float64(4.450085133743686),
 np.float64(2.0000802580152697),
 np.float64(1.0000803642413723),
 np.float64(6.390063083681561),
 np.float64(7.94006872854619),
 np.float64(24.950057758342265),
 np.float64(5.64007899514017),
 np.float64(25.780080803521678),
 np.float64(12.790051424514033),
 np.float64(29.92006887018589),
 np.float64(6.200065573538401),
 np.float64(189.63005850971115),
 np.float64(4.50006977460863),
 np.float64(7.593377812667793e-05),
 np.float64(1.1700714693463106),
 np.float64(4.840076921177243),
 np.float64(8.260083371267656),
 np.float64(151.6199286438893),
 np.float64(34.120055533332646),
 np.float64(40.27005873639679),
 np.float64(4.210068101705383),
 np.float64(8.039182867416311e-05),
 np.float64(1.24007319206408),
 np.float64(1.2200805462529496),
 np.float64(156.08001751755253),
 np.float64(10.300071591575666),
 np.float64(2.0600837291187113),
 np.float64(1.0000775848819385),
 np.float64(11.840073505889233),
 np.float64(12.45007503309813),
 np.float64(12.290073101882452),
 np.float64(1.6100782940414515),
 np.float64(6.750061292099425),
 np.float64(5.780070291090285),
 np.float64(9.000067367475589),
 np.float64(48.93004554385432),
 np.float64(19.320056041772848),
 np.float64(2.75007813106187),
 np.float64(1.0000786505441468),
 np.float64(3.080067148565925),
 np.float64(7.034201460556777e-05),
 np.float64(8.100067223442746),
 np.float64(80.96000818778207),
 np.float64(1.530079585341332),
 np.float64(3.1600558183930074),
 np.float64(8.330076071735222),
 np.float64(4.570057917985628),
 np.float64(7.000022117401252),
 np.float64(84.17003936433979),
 np.float64(1.0000724379364025),
 np.float64(1.2600784315446876),
 np.float64(10.300063678079708),
 np.float64(11.940061768485645),
 np.float64(3.9400787803429425),
 np.float64(2.2000764263197508),
 np.float64(33.85005002596964),
 np.float64(444.7299895458856),
 np.float64(0.8900807167075014),
 np.float64(2.8100696981499467),
 np.float64(8.308540105741741e-05),
 np.float64(7.160070557051853),
 np.float64(11.250075324720868),
 np.float64(6.150062813182002),
 np.float64(5.670080148524698),
 np.float64(8.195684346265497e-05),
 np.float64(18.270072860777276),
 np.float64(12.040060521105342),
 np.float64(2.6300721511698635),
 np.float64(2.40007078640604),
 np.float64(1.9800772502282702),
 np.float64(0.15008310870764302),
 np.float64(5.8900762224674),
 np.float64(1.0000694582808847),
 np.float64(8.690079830212383),
 np.float64(1.4400723497036336),
 np.float64(1.620070626949794),
 np.float64(129.48011976894603),
 np.float64(92.24995332642881),
 np.float64(7.90006982822047),
 np.float64(4.000055603910525),
 np.float64(25.03003411896521),
 np.float64(38.85005757476793),
 np.float64(7.330070732837076),
 np.float64(21.750064486670976),
 np.float64(2.7800319535983014),
 np.float64(1.6900838860315064),
 np.float64(19.000075647209922),
 np.float64(12.060074198793934),
 np.float64(3.980043973653128),
 np.float64(51.64000526068706),
 np.float64(120.02004463278817),
 np.float64(4.820074024894401),
 np.float64(10.240067214294125),
 np.float64(5.400075055269461),
 np.float64(18.290053659617993),
 np.float64(12.160051597487694),
 np.float64(14.000053484919864),
 np.float64(3.000057573165458),
 np.float64(1.00008250545445),
 np.float64(0.29006974648705874),
 np.float64(11.270074472578338),
 np.float64(6.000070715038175),
 np.float64(16.78006974645821),
 np.float64(7.146882803124588e-05),
 np.float64(11.88008977722092),
 np.float64(8.294259849281598e-05),
 np.float64(2.970076395404276),
 np.float64(0.9800776955318025),
 np.float64(7.380075762639498),
 np.float64(9.460046544144394),
 np.float64(8.76006839732262),
 np.float64(25.050061908324395),
 np.float64(97.95007689689523),
 np.float64(7.359440463905464e-05),
 np.float64(56.80006472879188),
 np.float64(3.0000715345146958),
 np.float64(18.430065522230063),
 np.float64(4.860075377978706),
 np.float64(19.80004295347662),
 np.float64(24.73005329840659),
 np.float64(10.100075818098794),
 np.float64(9.77009448336769),
 np.float64(4.100079141676714),
 np.float64(6.000056733558861),
 np.float64(18.380070835209434),
 np.float64(39.62003633112322),
 np.float64(51.69007048863905),
 np.float64(8.090051018317252),
 np.float64(20.150077077715025),
 np.float64(7.835961642306544e-05),
 np.float64(7.900646054199989e-05),
 np.float64(1.5000767502716639),
 np.float64(8.236384389523083e-05),
 np.float64(7.500098137752653e-05),
 np.float64(20.060078156851407),
 np.float64(1.0000799293923441),
 np.float64(1.5000766442830702),
 np.float64(2.3400813478749067),
 np.float64(16.210068920280644),

In [63]:
X_test.head()

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
281030,2005,9,209.0,34.0,10.12,0.19,8.88,0.0,1.0,0.0,2045.0,469.0,41.0,541.0,0.0,994.0
6930,2022,1,617.0,82.0,29.69,2.04,26.88,0.3,27.0,1.0,5410.0,2471.0,157.0,1095.0,15.0,1672.0
68406,2018,12,733.0,169.0,58.64,4.61,67.43,0.0,17.0,0.0,9497.0,3524.0,818.0,2633.0,0.0,2522.0
113309,2015,10,194.0,36.0,6.82,4.03,9.22,0.0,0.0,0.0,1575.0,249.0,91.0,317.0,0.0,918.0
239094,2007,12,90.0,24.0,9.79,2.56,1.75,0.0,2.0,0.0,1396.0,459.0,301.0,77.0,0.0,559.0

In [65]:
list (y_test.head())

[14.8, 23.08, 38.32, 15.92, 9.9]

In [66]:
from sklearn.metrics import mean_squared_error

In [67]:
MSEValue = mean_squared_error(y_test, y_pred, multioutput='uniform_average') # it can be raw_values
print('Mean Squared Error Value is : ', MSEValue)

Mean Squared Error Value is :  3.585733240885392e-05