In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("house_price_regression_dataset.csv")

In [3]:
data.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06

In [5]:
data.isna().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   int64
 1   Num_Bedrooms          1000 non-null   int64
 2   Num_Bathrooms         1000 non-null   int64
 3   Year_Built            1000 non-null   int64
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64
 6   Neighborhood_Quality  1000 non-null   int64
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB

In [12]:
data.shape

(1000, 8)

In [7]:
X = data.drop(["House_Price"] , axis = 1 ,inplace = False)
y = data["House_Price"]

In [8]:
X.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
0,1360,2,1,1981,0.599637,0,5
1,4272,3,3,2016,4.753014,1,6
2,3592,1,2,2016,3.634823,0,9
3,966,1,2,1977,2.730667,1,8
4,4926,2,1,1993,4.699073,0,8

In [11]:
X.shape

(1000, 7)

In [9]:
y.head()

0    2.623829e+05
1    9.852609e+05
2    7.779774e+05
3    2.296989e+05
4    1.041741e+06
Name: House_Price, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split

In [22]:
X_train,X_test,y_train,y_test = train_test_split(X , y , test_size = 0.2 , random_state = 44 , shuffle = True )

print('X_train shape is :' , X_train.shape)
print('X_test shape is :' , X_test.shape)
print('y_train shape is :' , y_train.shape)
print('y_test shape is :' , y_test.shape)

X_train shape is : (800, 7)
X_test shape is : (200, 7)
y_train shape is : (800,)
y_test shape is : (200,)

In [30]:
X_train.head()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality
49,3652,1,3,1994,2.810157,1,9
479,1010,2,2,1990,3.695597,0,4
50,2455,3,2,1953,4.951480,0,10
424,2643,3,1,1964,4.617346,0,5
83,2778,1,1,1991,3.481178,1,10

In [26]:
from sklearn.linear_model import LinearRegression

In [28]:
linear_regression_model = LinearRegression ( fit_intercept = True , copy_X = True , n_jobs = -1)

In [29]:
linear_regression_model.fit (X_train,y_train)

LinearRegression(n_jobs=-1)

In [41]:
y_pred = linear_regression_model.predict (X_test)
list (y_pred)

[np.float64(884725.1495418139),
 np.float64(654423.5211436227),
 np.float64(693420.3365046014),
 np.float64(492644.5698808348),
 np.float64(715188.5231174775),
 np.float64(233571.40100226412),
 np.float64(800618.3738078936),
 np.float64(429956.67120325286),
 np.float64(278090.5382885821),
 np.float64(769948.9316720129),
 np.float64(793660.9846366094),
 np.float64(348729.0455205217),
 np.float64(904285.3142086258),
 np.float64(736682.0347048789),
 np.float64(333973.4969932302),
 np.float64(678304.7072887225),
 np.float64(966275.7834772822),
 np.float64(659581.1592292353),
 np.float64(1017933.9835931342),
 np.float64(692406.5879685818),
 np.float64(433862.8810942448),
 np.float64(900214.1035011308),
 np.float64(219053.36760340305),
 np.float64(496783.35901417956),
 np.float64(845725.9839111543),
 np.float64(721186.3685509609),
 np.float64(906331.1809805366),
 np.float64(673690.2909898795),
 np.float64(623439.7851330619),
 np.float64(606264.6903913603),
 np.float64(415450.7094379682),
 np.float64(535782.2654453996),
 np.float64(889079.5181822716),
 np.float64(1006411.1379253562),
 np.float64(520807.4124797173),
 np.float64(777496.4030305911),
 np.float64(574121.3647239408),
 np.float64(827178.2754269666),
 np.float64(544061.7938294234),
 np.float64(646713.218236411),
 np.float64(421052.6994652883),
 np.float64(788627.418542909),
 np.float64(365996.3907852853),
 np.float64(547605.6859897878),
 np.float64(441085.9626248167),
 np.float64(380158.92267677747),
 np.float64(648992.6580640622),
 np.float64(117411.42692077067),
 np.float64(849242.8163799248),
 np.float64(929745.8661223939),
 np.float64(358782.71853767755),
 np.float64(404630.7529684659),
 np.float64(528758.2355943546),
 np.float64(686411.7131769555),
 np.float64(539000.7073478028),
 np.float64(895952.8248787094),
 np.float64(691836.5620885328),
 np.float64(241174.76268550195),
 np.float64(681730.9930639192),
 np.float64(1023891.8993827491),
 np.float64(732017.422374493),
 np.float64(266650.9876050195),
 np.float64(324423.8189986949),
 np.float64(451817.4648001003),
 np.float64(324570.4637727565),
 np.float64(662189.7961792611),
 np.float64(306024.1128855599),
 np.float64(931461.7723848997),
 np.float64(1010865.9124423941),
 np.float64(594410.7233908097),
 np.float64(907100.9504195033),
 np.float64(575754.3272278467),
 np.float64(978592.3304665331),
 np.float64(644239.1819781107),
 np.float64(994069.4607913666),
 np.float64(684722.3641546089),
 np.float64(909409.0778389568),
 np.float64(351395.20709900046),
 np.float64(302154.827530141),
 np.float64(317834.4480544175),
 np.float64(971944.7955889441),
 np.float64(820375.7994133444),
 np.float64(231270.87603895226),
 np.float64(825831.3559951345),
 np.float64(662848.2035896168),
 np.float64(1009698.9644224239),
 np.float64(868584.9265484065),
 np.float64(627029.1440130547),
 np.float64(214921.28363471013),
 np.float64(831316.6116225375),
 np.float64(1044056.1399875772),
 np.float64(220037.41093358677),
 np.float64(759172.6830965513),
 np.float64(738908.9730662596),
 np.float64(459410.1654716977),
 np.float64(885345.6098003085),
 np.float64(174330.61670364533),
 np.float64(569390.9406117406),
 np.float64(437334.5356698176),
 np.float64(786133.2789121871),
 np.float64(976352.9599241815),
 np.float64(308219.9605342145),
 np.float64(663350.4378948165),
 np.float64(755846.2080414905),
 np.float64(733070.2039273642),
 np.float64(1071767.8710149382),
 np.float64(1041072.755637533),
 np.float64(496121.4319978049),
 np.float64(382692.84824179066),
 np.float64(728898.6805720795),
 np.float64(218551.3466360811),
 np.float64(904870.3991431603),
 np.float64(1002477.3242228669),
 np.float64(1035147.4677903871),
 np.float64(708318.8728128574),
 np.float64(725730.4531254796),
 np.float64(780311.7672782899),
 np.float64(327074.01189738465),
 np.float64(794899.592045825),
 np.float64(774489.0684642242),
 np.float64(759786.3077636459),
 np.float64(948351.87936944),
 np.float64(877078.2278830847),
 np.float64(1082024.101304369),
 np.float64(401176.8385598203),
 np.float64(449848.2449533944),
 np.float64(629361.4288635016),
 np.float64(884624.0363095738),
 np.float64(615761.0520435385),
 np.float64(656366.6442310396),
 np.float64(892675.5285414057),
 np.float64(525471.1433101818),
 np.float64(622857.4775247062),
 np.float64(427967.3173995586),
 np.float64(355413.79521324625),
 np.float64(613741.2749317698),
 np.float64(860423.9023509598),
 np.float64(742597.4813348269),
 np.float64(548282.8926640521),
 np.float64(455818.62601204915),
 np.float64(761713.8040126329),
 np.float64(403894.03142866306),
 np.float64(181713.43599910894),
 np.float64(416164.74625971867),
 np.float64(774420.3520015795),
 np.float64(962904.558471391),
 np.float64(531655.0424607112),
 np.float64(534708.9100691127),
 np.float64(753391.3245448908),
 np.float64(833835.3148205653),
 np.float64(357341.8679533331),
 np.float64(437618.68394347746),
 np.float64(909439.8601101069),
 np.float64(711754.2132215253),
 np.float64(492910.3864116017),
 np.float64(819332.8461980666),
 np.float64(122391.35505807167),
 np.float64(243942.29194433708),
 np.float64(1035379.7618441544),
 np.float64(347848.0249222852),
 np.float64(818965.0337844477),
 np.float64(1103125.099559579),
 np.float64(943591.4094103212),
 np.float64(713881.6965202573),
 np.float64(505390.143554708),
 np.float64(540705.0227829362),
 np.float64(524711.9809866673),
 np.float64(759113.4797547618),
 np.float64(304114.37263496127),
 np.float64(164606.44762545824),
 np.float64(527796.02833843),
 np.float64(433171.6477216198),
 np.float64(996353.614034832),
 np.float64(625310.140067359),
 np.float64(514898.65572911873),
 np.float64(372180.67953272397),
 np.float64(511973.2003150126),
 np.float64(895511.3140171259),
 np.float64(903466.5450333208),
 np.float64(820095.677972632),
 np.float64(150178.26857409207),
 np.float64(503201.1735978052),
 np.float64(651598.2016114905),
 np.float64(925529.9100835957),
 np.float64(505815.71525310725),
 np.float64(681081.5891145943),
 np.float64(280498.642917925),
 np.float64(690249.7392315408),
 np.float64(531302.284506774),
 np.float64(515927.66178685986),
 np.float64(615916.9134904393),
 np.float64(757421.0295153451),
 np.float64(197926.5322627402),
 np.float64(793794.9486129056),
 np.float64(549134.1094349911),
 np.float64(940472.4956848593),
 np.float64(508988.49395785853),
 np.float64(253268.15661508963),
 np.float64(344635.77969665825),
 np.float64(819759.1135641686)]

In [42]:
list (y_test.head())

[886568.3132277146,
 672852.0519810001,
 697574.5556670319,
 481489.24616078194,
 728289.8873118911]

In [43]:
from sklearn.metrics import mean_squared_error

In [44]:
MSEValue = mean_squared_error(y_test, y_pred, multioutput='uniform_average') 
print('Mean Squared Error Value is : ', MSEValue)

Mean Squared Error Value is :  108597485.46644396

In [45]:
from sklearn.metrics import r2_score
print("Accuracy Score (R2):", r2_score(y_test, y_pred))

Accuracy Score (R2): 0.9981835704533782